# Generated by Django 6.0.4 on 2026-04-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_bankaccounttype_id_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='citizenship_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
