# Generated by Django 6.0.4 on 2026-04-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userbankaccount_citizenship_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='ifsc_code',
            field=models.CharField(default='BANK000123', max_length=20),
        ),
    ]
