# Generated by Django 6.0.4 on 2026-04-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='income_document',
            field=models.FileField(blank=True, null=True, upload_to='loan_documents/'),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('STUDENT', 'Student Loan'), ('HOUSE', 'House Loan'), ('COMMUNITY', 'Community Loan')], default='HOUSE', max_length=10),
        ),
    ]
